// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfonQyMRqHpdNZ9VOi7Nqlc6109Xf2UiM',
    appId: '1:982572565575:web:0a8b6a884660d204f09d62',
    messagingSenderId: '982572565575',
    projectId: 'healthapp-52e54',
    authDomain: 'healthapp-52e54.firebaseapp.com',
    storageBucket: 'healthapp-52e54.appspot.com',
    measurementId: 'G-VC090XQXFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPgKM6T_FKnnnolZpG-uv0cdplsmB354',
    appId: '1:982572565575:android:66e6a30f4c6d537bf09d62',
    messagingSenderId: '982572565575',
    projectId: 'healthapp-52e54',
    storageBucket: 'healthapp-52e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCri-EElNeAsinmNjsfaJd8BArwgMj_2bI',
    appId: '1:982572565575:ios:94b103b8dc7a4b87f09d62',
    messagingSenderId: '982572565575',
    projectId: 'healthapp-52e54',
    storageBucket: 'healthapp-52e54.appspot.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCri-EElNeAsinmNjsfaJd8BArwgMj_2bI',
    appId: '1:982572565575:ios:94b103b8dc7a4b87f09d62',
    messagingSenderId: '982572565575',
    projectId: 'healthapp-52e54',
    storageBucket: 'healthapp-52e54.appspot.com',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfonQyMRqHpdNZ9VOi7Nqlc6109Xf2UiM',
    appId: '1:982572565575:web:d8d491f37350dbeff09d62',
    messagingSenderId: '982572565575',
    projectId: 'healthapp-52e54',
    authDomain: 'healthapp-52e54.firebaseapp.com',
    storageBucket: 'healthapp-52e54.appspot.com',
    measurementId: 'G-HZ8B01Q7QJ',
  );
}
